### ISSUE TITLE
Mypy CI

### ISSUE THREAD

**Issue by martinlehoux** [martinlehoux/erp-reloaded#10]
## Description
Use `mypy` Python type checker.

## Roadmap
- [ ] Add Mypy package
- [ ] Add CI with `--strict`
- [ ] Fix all issues
